/** Scalar ships no Italian; these cover what the reference shows, and anything missing falls back to English. */
export const SCALAR_IT = {
	apiClient: {
		requestBlock: {
			cookies: "Cookie",
			headers: "Header",
			queryParameters: "Parametri della query",
			requestBody: "Corpo della richiesta",
		},
		responseBlock: {
			requestFailed: "Richiesta non riuscita",
			response: "Risposta",
			requestHeaders: "Header della richiesta",
			responseHeaders: "Header della risposta",
			body: "Corpo",
		},
		requestTable: { enabled: "Attivo", key: "Chiave", value: "Valore" },
		requestTableRow: {
			key: "Chiave",
			value: "Valore",
			delete: "Elimina",
			deleteRow: "Elimina la riga",
		},
		headers: { headerKey: "Header", headerValue: "Valore", noHeaders: "Nessun header" },
		responseBodyToggle: { preview: "Anteprima", raw: "Grezzo" },
		responseCookies: {
			cookies: "Cookie",
			cookieName: "Nome",
			cookieValue: "Valore",
			noCookies: "Nessun cookie",
		},
		responseEmpty: { sendRequest: "Invia la richiesta" },
		responseLoadingOverlay: { cancel: "Annulla" },
		addressBar: {
			path: "Percorso",
			copyUrl: "Copia l'URL",
			send: "Invia",
			sendRequest: "Invia la richiesta",
		},
		header: { closeClient: "Chiudi" },
		requestBody: { noBody: "Nessun corpo", none: "Nessuno", other: "Altro" },
	},
	common: {
		streamItem: "Elemento dello stream",
		description: "Descrizione",
		httpMethod: "Metodo HTTP",
		path: "Percorso",
		copyDefault: "Copia il valore predefinito",
		copyExample: "Copia l'esempio",
	},
	search: {
		label: "Cerca",
		inputLabel: "Testo da cercare",
		open: "Apri la ricerca",
		placeholder: "Cerca…",
		clear: "Svuota la ricerca",
		noResults: "Nessun risultato",
		results: "Risultati della ricerca",
		navigate: "Muoviti",
		select: "Seleziona",
	},
	navigation: {
		introduction: "Introduzione",
		operations: "Operazioni",
		endpoints: "Endpoint di {name}",
		showAllEndpoints: "Mostra tutti gli endpoint di {name}",
		mainContent: "Documentazione di {name}",
	},
	server: { label: "Server", select: "Scegli un server" },
	clientLibraries: {
		heading: "Esempi di codice",
		more: "Altri",
		selectAll: "Scegli fra tutti i client",
		searchLabel: "Cerca un client",
		changeClient: "Cambia il linguaggio dell'esempio",
	},
	operation: {
		codeSampleUnavailable: "Nessun esempio di codice per questa chiamata.",
		codeSample: "Esempio di codice",
		body: "Corpo",
		headers: "Header",
		pathParameters: "Parametri del percorso",
		queryParameters: "Parametri della query",
		requestBody: "Corpo della richiesta",
		responses: "Risposte",
		testRequest: "Prova",
		selectedContentType: "Tipo di contenuto",
	},
	response: {
		exampleResponses: "Risposte di esempio",
		noBody: "Nessun corpo",
		showSchema: "Mostra lo schema",
		status: "Stato",
	},
	schema: {
		example: "Esempio",
		examples: "Esempi",
		default: "Predefinito",
		schema: "Schema",
		emptyObject: "Oggetto vuoto",
		showAdditionalProperties: "Mostra le proprietà aggiuntive",
		showOneMoreProperty: "Mostra un'altra proprietà",
		showMoreProperties: "Mostra altre {count} proprietà",
		showSchemaDetails: "Mostra i dettagli dello schema",
		oneOf: "Uno fra",
		anyOf: "Almeno uno fra",
		allOf: "Tutti",
		unknownType: "tipo sconosciuto",
		propertyCount: "Proprietà: {count}",
		additionalProperties: "proprietà aggiuntive",
		required: "obbligatorio",
		nullable: "nullabile",
		hideValues: "Nascondi i valori",
		showAllValues: "Mostra tutti i valori",
		type: "Tipo",
		values: "valori",
	},
	download: {
		openapi: "Scarica il documento OpenAPI",
		asFormat: "{label} in {format}",
	},
	models: { label: "Modelli" },
	actions: {
		copyAsMarkdown: "Copia in Markdown",
		copied: "Copiato",
		copyMarkdownFailed: "Copia non riuscita",
		copyLink: "Copia il link",
		copyLinkTo: "Copia il link a {name}",
		copyToClipboard: "Copia il link",
		copyEndpointUrl: "Copia l'URL dell'endpoint",
		showMore: "Mostra di più",
	},
};
