/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ActivityRouteImport } from './routes/activity'
import { Route as IndexRouteImport } from './routes/index'
import { Route as StagingIndexRouteImport } from './routes/staging/index'
import { Route as SourcesIndexRouteImport } from './routes/sources/index'
import { Route as SettingsIndexRouteImport } from './routes/settings/index'
import { Route as JobsIndexRouteImport } from './routes/jobs/index'
import { Route as StagingPromotionsRouteImport } from './routes/staging/promotions'
import { Route as SourcesTimetablesRouteImport } from './routes/sources/timetables'
import { Route as SourcesSyllabiRouteImport } from './routes/sources/syllabi'
import { Route as SourcesExamsRouteImport } from './routes/sources/exams'
import { Route as SourcesCatalogRouteImport } from './routes/sources/catalog'
import { Route as SettingsAccessRouteImport } from './routes/settings/access'
import { Route as JobsSchedulesRouteImport } from './routes/jobs/schedules'

const ActivityRoute = ActivityRouteImport.update({
  id: '/activity',
  path: '/activity',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const StagingIndexRoute = StagingIndexRouteImport.update({
  id: '/staging/',
  path: '/staging/',
  getParentRoute: () => rootRouteImport,
} as any)
const SourcesIndexRoute = SourcesIndexRouteImport.update({
  id: '/sources/',
  path: '/sources/',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsIndexRoute = SettingsIndexRouteImport.update({
  id: '/settings/',
  path: '/settings/',
  getParentRoute: () => rootRouteImport,
} as any)
const JobsIndexRoute = JobsIndexRouteImport.update({
  id: '/jobs/',
  path: '/jobs/',
  getParentRoute: () => rootRouteImport,
} as any)
const StagingPromotionsRoute = StagingPromotionsRouteImport.update({
  id: '/staging/promotions',
  path: '/staging/promotions',
  getParentRoute: () => rootRouteImport,
} as any)
const SourcesTimetablesRoute = SourcesTimetablesRouteImport.update({
  id: '/sources/timetables',
  path: '/sources/timetables',
  getParentRoute: () => rootRouteImport,
} as any)
const SourcesSyllabiRoute = SourcesSyllabiRouteImport.update({
  id: '/sources/syllabi',
  path: '/sources/syllabi',
  getParentRoute: () => rootRouteImport,
} as any)
const SourcesExamsRoute = SourcesExamsRouteImport.update({
  id: '/sources/exams',
  path: '/sources/exams',
  getParentRoute: () => rootRouteImport,
} as any)
const SourcesCatalogRoute = SourcesCatalogRouteImport.update({
  id: '/sources/catalog',
  path: '/sources/catalog',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsAccessRoute = SettingsAccessRouteImport.update({
  id: '/settings/access',
  path: '/settings/access',
  getParentRoute: () => rootRouteImport,
} as any)
const JobsSchedulesRoute = JobsSchedulesRouteImport.update({
  id: '/jobs/schedules',
  path: '/jobs/schedules',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/activity': typeof ActivityRoute
  '/jobs/schedules': typeof JobsSchedulesRoute
  '/settings/access': typeof SettingsAccessRoute
  '/sources/catalog': typeof SourcesCatalogRoute
  '/sources/exams': typeof SourcesExamsRoute
  '/sources/syllabi': typeof SourcesSyllabiRoute
  '/sources/timetables': typeof SourcesTimetablesRoute
  '/staging/promotions': typeof StagingPromotionsRoute
  '/jobs/': typeof JobsIndexRoute
  '/settings/': typeof SettingsIndexRoute
  '/sources/': typeof SourcesIndexRoute
  '/staging/': typeof StagingIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/activity': typeof ActivityRoute
  '/jobs/schedules': typeof JobsSchedulesRoute
  '/settings/access': typeof SettingsAccessRoute
  '/sources/catalog': typeof SourcesCatalogRoute
  '/sources/exams': typeof SourcesExamsRoute
  '/sources/syllabi': typeof SourcesSyllabiRoute
  '/sources/timetables': typeof SourcesTimetablesRoute
  '/staging/promotions': typeof StagingPromotionsRoute
  '/jobs': typeof JobsIndexRoute
  '/settings': typeof SettingsIndexRoute
  '/sources': typeof SourcesIndexRoute
  '/staging': typeof StagingIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/activity': typeof ActivityRoute
  '/jobs/schedules': typeof JobsSchedulesRoute
  '/settings/access': typeof SettingsAccessRoute
  '/sources/catalog': typeof SourcesCatalogRoute
  '/sources/exams': typeof SourcesExamsRoute
  '/sources/syllabi': typeof SourcesSyllabiRoute
  '/sources/timetables': typeof SourcesTimetablesRoute
  '/staging/promotions': typeof StagingPromotionsRoute
  '/jobs/': typeof JobsIndexRoute
  '/settings/': typeof SettingsIndexRoute
  '/sources/': typeof SourcesIndexRoute
  '/staging/': typeof StagingIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/activity'
    | '/jobs/schedules'
    | '/settings/access'
    | '/sources/catalog'
    | '/sources/exams'
    | '/sources/syllabi'
    | '/sources/timetables'
    | '/staging/promotions'
    | '/jobs/'
    | '/settings/'
    | '/sources/'
    | '/staging/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/activity'
    | '/jobs/schedules'
    | '/settings/access'
    | '/sources/catalog'
    | '/sources/exams'
    | '/sources/syllabi'
    | '/sources/timetables'
    | '/staging/promotions'
    | '/jobs'
    | '/settings'
    | '/sources'
    | '/staging'
  id:
    | '__root__'
    | '/'
    | '/activity'
    | '/jobs/schedules'
    | '/settings/access'
    | '/sources/catalog'
    | '/sources/exams'
    | '/sources/syllabi'
    | '/sources/timetables'
    | '/staging/promotions'
    | '/jobs/'
    | '/settings/'
    | '/sources/'
    | '/staging/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ActivityRoute: typeof ActivityRoute
  JobsSchedulesRoute: typeof JobsSchedulesRoute
  SettingsAccessRoute: typeof SettingsAccessRoute
  SourcesCatalogRoute: typeof SourcesCatalogRoute
  SourcesExamsRoute: typeof SourcesExamsRoute
  SourcesSyllabiRoute: typeof SourcesSyllabiRoute
  SourcesTimetablesRoute: typeof SourcesTimetablesRoute
  StagingPromotionsRoute: typeof StagingPromotionsRoute
  JobsIndexRoute: typeof JobsIndexRoute
  SettingsIndexRoute: typeof SettingsIndexRoute
  SourcesIndexRoute: typeof SourcesIndexRoute
  StagingIndexRoute: typeof StagingIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/activity': {
      id: '/activity'
      path: '/activity'
      fullPath: '/activity'
      preLoaderRoute: typeof ActivityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/staging/': {
      id: '/staging/'
      path: '/staging'
      fullPath: '/staging/'
      preLoaderRoute: typeof StagingIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sources/': {
      id: '/sources/'
      path: '/sources'
      fullPath: '/sources/'
      preLoaderRoute: typeof SourcesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/': {
      id: '/settings/'
      path: '/settings'
      fullPath: '/settings/'
      preLoaderRoute: typeof SettingsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/jobs/': {
      id: '/jobs/'
      path: '/jobs'
      fullPath: '/jobs/'
      preLoaderRoute: typeof JobsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/staging/promotions': {
      id: '/staging/promotions'
      path: '/staging/promotions'
      fullPath: '/staging/promotions'
      preLoaderRoute: typeof StagingPromotionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sources/timetables': {
      id: '/sources/timetables'
      path: '/sources/timetables'
      fullPath: '/sources/timetables'
      preLoaderRoute: typeof SourcesTimetablesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sources/syllabi': {
      id: '/sources/syllabi'
      path: '/sources/syllabi'
      fullPath: '/sources/syllabi'
      preLoaderRoute: typeof SourcesSyllabiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sources/exams': {
      id: '/sources/exams'
      path: '/sources/exams'
      fullPath: '/sources/exams'
      preLoaderRoute: typeof SourcesExamsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sources/catalog': {
      id: '/sources/catalog'
      path: '/sources/catalog'
      fullPath: '/sources/catalog'
      preLoaderRoute: typeof SourcesCatalogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/access': {
      id: '/settings/access'
      path: '/settings/access'
      fullPath: '/settings/access'
      preLoaderRoute: typeof SettingsAccessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/jobs/schedules': {
      id: '/jobs/schedules'
      path: '/jobs/schedules'
      fullPath: '/jobs/schedules'
      preLoaderRoute: typeof JobsSchedulesRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ActivityRoute: ActivityRoute,
  JobsSchedulesRoute: JobsSchedulesRoute,
  SettingsAccessRoute: SettingsAccessRoute,
  SourcesCatalogRoute: SourcesCatalogRoute,
  SourcesExamsRoute: SourcesExamsRoute,
  SourcesSyllabiRoute: SourcesSyllabiRoute,
  SourcesTimetablesRoute: SourcesTimetablesRoute,
  StagingPromotionsRoute: StagingPromotionsRoute,
  JobsIndexRoute: JobsIndexRoute,
  SettingsIndexRoute: SettingsIndexRoute,
  SourcesIndexRoute: SourcesIndexRoute,
  StagingIndexRoute: StagingIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
