/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ConsoleRouteRouteImport } from './routes/_console/route'
import { Route as ConsoleIndexRouteImport } from './routes/_console/index'
import { Route as AuthCallbackRouteImport } from './routes/auth/callback'
import { Route as ApiProxyRouteImport } from './routes/api/proxy'
import { Route as ConsoleApisRouteImport } from './routes/_console/apis'
import { Route as ConsoleActivityRouteImport } from './routes/_console/activity'
import { Route as ConsoleSourcesIndexRouteImport } from './routes/_console/sources/index'
import { Route as ConsoleSettingsIndexRouteImport } from './routes/_console/settings/index'
import { Route as ConsoleJobsIndexRouteImport } from './routes/_console/jobs/index'
import { Route as ConsoleSourcesTimetablesRouteImport } from './routes/_console/sources/timetables'
import { Route as ConsoleSourcesExamsRouteImport } from './routes/_console/sources/exams'
import { Route as ConsoleSourcesClassesRouteImport } from './routes/_console/sources/classes'
import { Route as ConsoleSourcesCatalogRouteImport } from './routes/_console/sources/catalog'
import { Route as ConsoleSettingsAccessRouteImport } from './routes/_console/settings/access'
import { Route as ConsoleJobsSchedulesRouteImport } from './routes/_console/jobs/schedules'
import { Route as ConsoleJobsRunsRouteImport } from './routes/_console/jobs/runs'
import { Route as ConsoleJobsJobIndexRouteImport } from './routes/_console/jobs/$job/index'
import { Route as ConsoleJobsJobRunsRunIdRouteImport } from './routes/_console/jobs/$job/runs/$runId'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ConsoleRouteRoute = ConsoleRouteRouteImport.update({
  id: '/_console',
  getParentRoute: () => rootRouteImport,
} as any)
const ConsoleIndexRoute = ConsoleIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ConsoleRouteRoute,
} as any)
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/auth/callback',
  path: '/auth/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiProxyRoute = ApiProxyRouteImport.update({
  id: '/api/proxy',
  path: '/api/proxy',
  getParentRoute: () => rootRouteImport,
} as any)
const ConsoleApisRoute = ConsoleApisRouteImport.update({
  id: '/apis',
  path: '/apis',
  getParentRoute: () => ConsoleRouteRoute,
} as any)
const ConsoleActivityRoute = ConsoleActivityRouteImport.update({
  id: '/activity',
  path: '/activity',
  getParentRoute: () => ConsoleRouteRoute,
} as any)
const ConsoleSourcesIndexRoute = ConsoleSourcesIndexRouteImport.update({
  id: '/sources/',
  path: '/sources/',
  getParentRoute: () => ConsoleRouteRoute,
} as any)
const ConsoleSettingsIndexRoute = ConsoleSettingsIndexRouteImport.update({
  id: '/settings/',
  path: '/settings/',
  getParentRoute: () => ConsoleRouteRoute,
} as any)
const ConsoleJobsIndexRoute = ConsoleJobsIndexRouteImport.update({
  id: '/jobs/',
  path: '/jobs/',
  getParentRoute: () => ConsoleRouteRoute,
} as any)
const ConsoleSourcesTimetablesRoute =
  ConsoleSourcesTimetablesRouteImport.update({
    id: '/sources/timetables',
    path: '/sources/timetables',
    getParentRoute: () => ConsoleRouteRoute,
  } as any)
const ConsoleSourcesExamsRoute = ConsoleSourcesExamsRouteImport.update({
  id: '/sources/exams',
  path: '/sources/exams',
  getParentRoute: () => ConsoleRouteRoute,
} as any)
const ConsoleSourcesClassesRoute = ConsoleSourcesClassesRouteImport.update({
  id: '/sources/classes',
  path: '/sources/classes',
  getParentRoute: () => ConsoleRouteRoute,
} as any)
const ConsoleSourcesCatalogRoute = ConsoleSourcesCatalogRouteImport.update({
  id: '/sources/catalog',
  path: '/sources/catalog',
  getParentRoute: () => ConsoleRouteRoute,
} as any)
const ConsoleSettingsAccessRoute = ConsoleSettingsAccessRouteImport.update({
  id: '/settings/access',
  path: '/settings/access',
  getParentRoute: () => ConsoleRouteRoute,
} as any)
const ConsoleJobsSchedulesRoute = ConsoleJobsSchedulesRouteImport.update({
  id: '/jobs/schedules',
  path: '/jobs/schedules',
  getParentRoute: () => ConsoleRouteRoute,
} as any)
const ConsoleJobsRunsRoute = ConsoleJobsRunsRouteImport.update({
  id: '/jobs/runs',
  path: '/jobs/runs',
  getParentRoute: () => ConsoleRouteRoute,
} as any)
const ConsoleJobsJobIndexRoute = ConsoleJobsJobIndexRouteImport.update({
  id: '/jobs/$job/',
  path: '/jobs/$job/',
  getParentRoute: () => ConsoleRouteRoute,
} as any)
const ConsoleJobsJobRunsRunIdRoute = ConsoleJobsJobRunsRunIdRouteImport.update({
  id: '/jobs/$job/runs/$runId',
  path: '/jobs/$job/runs/$runId',
  getParentRoute: () => ConsoleRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof ConsoleIndexRoute
  '/login': typeof LoginRoute
  '/activity': typeof ConsoleActivityRoute
  '/apis': typeof ConsoleApisRoute
  '/api/proxy': typeof ApiProxyRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/jobs/runs': typeof ConsoleJobsRunsRoute
  '/jobs/schedules': typeof ConsoleJobsSchedulesRoute
  '/settings/access': typeof ConsoleSettingsAccessRoute
  '/sources/catalog': typeof ConsoleSourcesCatalogRoute
  '/sources/classes': typeof ConsoleSourcesClassesRoute
  '/sources/exams': typeof ConsoleSourcesExamsRoute
  '/sources/timetables': typeof ConsoleSourcesTimetablesRoute
  '/jobs/': typeof ConsoleJobsIndexRoute
  '/settings/': typeof ConsoleSettingsIndexRoute
  '/sources/': typeof ConsoleSourcesIndexRoute
  '/jobs/$job/': typeof ConsoleJobsJobIndexRoute
  '/jobs/$job/runs/$runId': typeof ConsoleJobsJobRunsRunIdRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/activity': typeof ConsoleActivityRoute
  '/apis': typeof ConsoleApisRoute
  '/api/proxy': typeof ApiProxyRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/': typeof ConsoleIndexRoute
  '/jobs/runs': typeof ConsoleJobsRunsRoute
  '/jobs/schedules': typeof ConsoleJobsSchedulesRoute
  '/settings/access': typeof ConsoleSettingsAccessRoute
  '/sources/catalog': typeof ConsoleSourcesCatalogRoute
  '/sources/classes': typeof ConsoleSourcesClassesRoute
  '/sources/exams': typeof ConsoleSourcesExamsRoute
  '/sources/timetables': typeof ConsoleSourcesTimetablesRoute
  '/jobs': typeof ConsoleJobsIndexRoute
  '/settings': typeof ConsoleSettingsIndexRoute
  '/sources': typeof ConsoleSourcesIndexRoute
  '/jobs/$job': typeof ConsoleJobsJobIndexRoute
  '/jobs/$job/runs/$runId': typeof ConsoleJobsJobRunsRunIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_console': typeof ConsoleRouteRouteWithChildren
  '/login': typeof LoginRoute
  '/_console/activity': typeof ConsoleActivityRoute
  '/_console/apis': typeof ConsoleApisRoute
  '/api/proxy': typeof ApiProxyRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/_console/': typeof ConsoleIndexRoute
  '/_console/jobs/runs': typeof ConsoleJobsRunsRoute
  '/_console/jobs/schedules': typeof ConsoleJobsSchedulesRoute
  '/_console/settings/access': typeof ConsoleSettingsAccessRoute
  '/_console/sources/catalog': typeof ConsoleSourcesCatalogRoute
  '/_console/sources/classes': typeof ConsoleSourcesClassesRoute
  '/_console/sources/exams': typeof ConsoleSourcesExamsRoute
  '/_console/sources/timetables': typeof ConsoleSourcesTimetablesRoute
  '/_console/jobs/': typeof ConsoleJobsIndexRoute
  '/_console/settings/': typeof ConsoleSettingsIndexRoute
  '/_console/sources/': typeof ConsoleSourcesIndexRoute
  '/_console/jobs/$job/': typeof ConsoleJobsJobIndexRoute
  '/_console/jobs/$job/runs/$runId': typeof ConsoleJobsJobRunsRunIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/activity'
    | '/apis'
    | '/api/proxy'
    | '/auth/callback'
    | '/jobs/runs'
    | '/jobs/schedules'
    | '/settings/access'
    | '/sources/catalog'
    | '/sources/classes'
    | '/sources/exams'
    | '/sources/timetables'
    | '/jobs/'
    | '/settings/'
    | '/sources/'
    | '/jobs/$job/'
    | '/jobs/$job/runs/$runId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/activity'
    | '/apis'
    | '/api/proxy'
    | '/auth/callback'
    | '/'
    | '/jobs/runs'
    | '/jobs/schedules'
    | '/settings/access'
    | '/sources/catalog'
    | '/sources/classes'
    | '/sources/exams'
    | '/sources/timetables'
    | '/jobs'
    | '/settings'
    | '/sources'
    | '/jobs/$job'
    | '/jobs/$job/runs/$runId'
  id:
    | '__root__'
    | '/_console'
    | '/login'
    | '/_console/activity'
    | '/_console/apis'
    | '/api/proxy'
    | '/auth/callback'
    | '/_console/'
    | '/_console/jobs/runs'
    | '/_console/jobs/schedules'
    | '/_console/settings/access'
    | '/_console/sources/catalog'
    | '/_console/sources/classes'
    | '/_console/sources/exams'
    | '/_console/sources/timetables'
    | '/_console/jobs/'
    | '/_console/settings/'
    | '/_console/sources/'
    | '/_console/jobs/$job/'
    | '/_console/jobs/$job/runs/$runId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  ConsoleRouteRoute: typeof ConsoleRouteRouteWithChildren
  LoginRoute: typeof LoginRoute
  ApiProxyRoute: typeof ApiProxyRoute
  AuthCallbackRoute: typeof AuthCallbackRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_console': {
      id: '/_console'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof ConsoleRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_console/': {
      id: '/_console/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof ConsoleIndexRouteImport
      parentRoute: typeof ConsoleRouteRoute
    }
    '/auth/callback': {
      id: '/auth/callback'
      path: '/auth/callback'
      fullPath: '/auth/callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/proxy': {
      id: '/api/proxy'
      path: '/api/proxy'
      fullPath: '/api/proxy'
      preLoaderRoute: typeof ApiProxyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_console/apis': {
      id: '/_console/apis'
      path: '/apis'
      fullPath: '/apis'
      preLoaderRoute: typeof ConsoleApisRouteImport
      parentRoute: typeof ConsoleRouteRoute
    }
    '/_console/activity': {
      id: '/_console/activity'
      path: '/activity'
      fullPath: '/activity'
      preLoaderRoute: typeof ConsoleActivityRouteImport
      parentRoute: typeof ConsoleRouteRoute
    }
    '/_console/sources/': {
      id: '/_console/sources/'
      path: '/sources'
      fullPath: '/sources/'
      preLoaderRoute: typeof ConsoleSourcesIndexRouteImport
      parentRoute: typeof ConsoleRouteRoute
    }
    '/_console/settings/': {
      id: '/_console/settings/'
      path: '/settings'
      fullPath: '/settings/'
      preLoaderRoute: typeof ConsoleSettingsIndexRouteImport
      parentRoute: typeof ConsoleRouteRoute
    }
    '/_console/jobs/': {
      id: '/_console/jobs/'
      path: '/jobs'
      fullPath: '/jobs/'
      preLoaderRoute: typeof ConsoleJobsIndexRouteImport
      parentRoute: typeof ConsoleRouteRoute
    }
    '/_console/sources/timetables': {
      id: '/_console/sources/timetables'
      path: '/sources/timetables'
      fullPath: '/sources/timetables'
      preLoaderRoute: typeof ConsoleSourcesTimetablesRouteImport
      parentRoute: typeof ConsoleRouteRoute
    }
    '/_console/sources/exams': {
      id: '/_console/sources/exams'
      path: '/sources/exams'
      fullPath: '/sources/exams'
      preLoaderRoute: typeof ConsoleSourcesExamsRouteImport
      parentRoute: typeof ConsoleRouteRoute
    }
    '/_console/sources/classes': {
      id: '/_console/sources/classes'
      path: '/sources/classes'
      fullPath: '/sources/classes'
      preLoaderRoute: typeof ConsoleSourcesClassesRouteImport
      parentRoute: typeof ConsoleRouteRoute
    }
    '/_console/sources/catalog': {
      id: '/_console/sources/catalog'
      path: '/sources/catalog'
      fullPath: '/sources/catalog'
      preLoaderRoute: typeof ConsoleSourcesCatalogRouteImport
      parentRoute: typeof ConsoleRouteRoute
    }
    '/_console/settings/access': {
      id: '/_console/settings/access'
      path: '/settings/access'
      fullPath: '/settings/access'
      preLoaderRoute: typeof ConsoleSettingsAccessRouteImport
      parentRoute: typeof ConsoleRouteRoute
    }
    '/_console/jobs/schedules': {
      id: '/_console/jobs/schedules'
      path: '/jobs/schedules'
      fullPath: '/jobs/schedules'
      preLoaderRoute: typeof ConsoleJobsSchedulesRouteImport
      parentRoute: typeof ConsoleRouteRoute
    }
    '/_console/jobs/runs': {
      id: '/_console/jobs/runs'
      path: '/jobs/runs'
      fullPath: '/jobs/runs'
      preLoaderRoute: typeof ConsoleJobsRunsRouteImport
      parentRoute: typeof ConsoleRouteRoute
    }
    '/_console/jobs/$job/': {
      id: '/_console/jobs/$job/'
      path: '/jobs/$job'
      fullPath: '/jobs/$job/'
      preLoaderRoute: typeof ConsoleJobsJobIndexRouteImport
      parentRoute: typeof ConsoleRouteRoute
    }
    '/_console/jobs/$job/runs/$runId': {
      id: '/_console/jobs/$job/runs/$runId'
      path: '/jobs/$job/runs/$runId'
      fullPath: '/jobs/$job/runs/$runId'
      preLoaderRoute: typeof ConsoleJobsJobRunsRunIdRouteImport
      parentRoute: typeof ConsoleRouteRoute
    }
  }
}

interface ConsoleRouteRouteChildren {
  ConsoleActivityRoute: typeof ConsoleActivityRoute
  ConsoleApisRoute: typeof ConsoleApisRoute
  ConsoleIndexRoute: typeof ConsoleIndexRoute
  ConsoleJobsRunsRoute: typeof ConsoleJobsRunsRoute
  ConsoleJobsSchedulesRoute: typeof ConsoleJobsSchedulesRoute
  ConsoleSettingsAccessRoute: typeof ConsoleSettingsAccessRoute
  ConsoleSourcesCatalogRoute: typeof ConsoleSourcesCatalogRoute
  ConsoleSourcesClassesRoute: typeof ConsoleSourcesClassesRoute
  ConsoleSourcesExamsRoute: typeof ConsoleSourcesExamsRoute
  ConsoleSourcesTimetablesRoute: typeof ConsoleSourcesTimetablesRoute
  ConsoleJobsIndexRoute: typeof ConsoleJobsIndexRoute
  ConsoleSettingsIndexRoute: typeof ConsoleSettingsIndexRoute
  ConsoleSourcesIndexRoute: typeof ConsoleSourcesIndexRoute
  ConsoleJobsJobIndexRoute: typeof ConsoleJobsJobIndexRoute
  ConsoleJobsJobRunsRunIdRoute: typeof ConsoleJobsJobRunsRunIdRoute
}

const ConsoleRouteRouteChildren: ConsoleRouteRouteChildren = {
  ConsoleActivityRoute: ConsoleActivityRoute,
  ConsoleApisRoute: ConsoleApisRoute,
  ConsoleIndexRoute: ConsoleIndexRoute,
  ConsoleJobsRunsRoute: ConsoleJobsRunsRoute,
  ConsoleJobsSchedulesRoute: ConsoleJobsSchedulesRoute,
  ConsoleSettingsAccessRoute: ConsoleSettingsAccessRoute,
  ConsoleSourcesCatalogRoute: ConsoleSourcesCatalogRoute,
  ConsoleSourcesClassesRoute: ConsoleSourcesClassesRoute,
  ConsoleSourcesExamsRoute: ConsoleSourcesExamsRoute,
  ConsoleSourcesTimetablesRoute: ConsoleSourcesTimetablesRoute,
  ConsoleJobsIndexRoute: ConsoleJobsIndexRoute,
  ConsoleSettingsIndexRoute: ConsoleSettingsIndexRoute,
  ConsoleSourcesIndexRoute: ConsoleSourcesIndexRoute,
  ConsoleJobsJobIndexRoute: ConsoleJobsJobIndexRoute,
  ConsoleJobsJobRunsRunIdRoute: ConsoleJobsJobRunsRunIdRoute,
}

const ConsoleRouteRouteWithChildren = ConsoleRouteRoute._addFileChildren(
  ConsoleRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  ConsoleRouteRoute: ConsoleRouteRouteWithChildren,
  LoginRoute: LoginRoute,
  ApiProxyRoute: ApiProxyRoute,
  AuthCallbackRoute: AuthCallbackRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
