/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as MaintenanceRouteImport } from './routes/maintenance'
import { Route as AppRouteImport } from './routes/_app'
import { Route as AppIndexRouteImport } from './routes/_app/index'
import { Route as QuizQuizIdRouteImport } from './routes/quiz/$quizId'
import { Route as FlashcardSessionIdRouteImport } from './routes/flashcard/$sessionId'
import { Route as AuthRegisterRouteImport } from './routes/auth/register'
import { Route as AuthLoginRouteImport } from './routes/auth/login'
import { Route as AuthCallbackRouteImport } from './routes/auth/callback'
import { Route as AppNewsRouteImport } from './routes/_app/news'
import { Route as AppContactRouteImport } from './routes/_app/contact'
import { Route as AppAboutRouteImport } from './routes/_app/about'
import { Route as AppUserRouteRouteImport } from './routes/_app/user/route'
import { Route as AppLegalRouteRouteImport } from './routes/_app/legal/route'
import { Route as AppAdminRouteRouteImport } from './routes/_app/admin/route'
import { Route as AppUserIndexRouteImport } from './routes/_app/user/index'
import { Route as AppDepartmentsIndexRouteImport } from './routes/_app/departments/index'
import { Route as AppBrowseIndexRouteImport } from './routes/_app/browse/index'
import { Route as AppAdminIndexRouteImport } from './routes/_app/admin/index'
import { Route as AppUserSettingsRouteImport } from './routes/_app/user/settings'
import { Route as AppUserProgressRouteImport } from './routes/_app/user/progress'
import { Route as AppUserNotificationsRouteImport } from './routes/_app/user/notifications'
import { Route as AppUserClassesRouteImport } from './routes/_app/user/classes'
import { Route as AppUserBookmarksRouteImport } from './routes/_app/user/bookmarks'
import { Route as AppLegalTermsRouteImport } from './routes/_app/legal/terms'
import { Route as AppLegalPrivacyRouteImport } from './routes/_app/legal/privacy'
import { Route as AppLegalDeclinedRouteImport } from './routes/_app/legal/declined'
import { Route as AppLegalCookiesRouteImport } from './routes/_app/legal/cookies'
import { Route as AppLegalAcceptRouteImport } from './routes/_app/legal/accept'
import { Route as AppUserRequestsIndexRouteImport } from './routes/_app/user/requests/index'
import { Route as AppSearchCoursesIndexRouteImport } from './routes/_app/search/courses/index'
import { Route as AppSearchClassesIndexRouteImport } from './routes/_app/search/classes/index'
import { Route as AppDepartmentsDepartmentIndexRouteImport } from './routes/_app/departments/$department/index'
import { Route as AppBrowseDepartmentIndexRouteImport } from './routes/_app/browse/$department/index'
import { Route as AppAdminUsersIndexRouteImport } from './routes/_app/admin/users/index'
import { Route as AppAdminRequestsIndexRouteImport } from './routes/_app/admin/requests/index'
import { Route as AppAdminDepartmentsIndexRouteImport } from './routes/_app/admin/departments/index'
import { Route as AppQuizResultsAttemptIdRouteImport } from './routes/_app/quiz.results.$attemptId'
import { Route as AppAdminUsersUserIdRouteImport } from './routes/_app/admin/users/$userId'
import { Route as AppAdminSectionsSectionIdRouteImport } from './routes/_app/admin/sections/$sectionId'
import { Route as AppAdminRequestsRequestIdRouteImport } from './routes/_app/admin/requests/$requestId'
import { Route as AppAdminQuestionsQuestionIdRouteImport } from './routes/_app/admin/questions/$questionId'
import { Route as AppAdminDepartmentsDepartmentIdRouteImport } from './routes/_app/admin/departments/$departmentId'
import { Route as AppAdminCoursesCourseIdRouteImport } from './routes/_app/admin/courses/$courseId'
import { Route as AppAdminClassesClassIdRouteImport } from './routes/_app/admin/classes/$classId'
import { Route as AppDepartmentsDepartmentCourseIndexRouteImport } from './routes/_app/departments/$department/$course/index'
import { Route as AppBrowseDepartmentCourseIndexRouteImport } from './routes/_app/browse/$department/$course/index'
import { Route as AppDepartmentsDepartmentCourseClassIndexRouteImport } from './routes/_app/departments/$department/$course/$class/index'
import { Route as AppBrowseDepartmentCourseClassIndexRouteImport } from './routes/_app/browse/$department/$course/$class/index'
import { Route as AppDepartmentsDepartmentCourseClassSectionIndexRouteImport } from './routes/_app/departments/$department/$course/$class/$section/index'
import { Route as AppBrowseDepartmentCourseClassSectionIndexRouteImport } from './routes/_app/browse/$department/$course/$class/$section/index'

const MaintenanceRoute = MaintenanceRouteImport.update({
  id: '/maintenance',
  path: '/maintenance',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const QuizQuizIdRoute = QuizQuizIdRouteImport.update({
  id: '/quiz/$quizId',
  path: '/quiz/$quizId',
  getParentRoute: () => rootRouteImport,
} as any)
const FlashcardSessionIdRoute = FlashcardSessionIdRouteImport.update({
  id: '/flashcard/$sessionId',
  path: '/flashcard/$sessionId',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRegisterRoute = AuthRegisterRouteImport.update({
  id: '/auth/register',
  path: '/auth/register',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/auth/login',
  path: '/auth/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/auth/callback',
  path: '/auth/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const AppNewsRoute = AppNewsRouteImport.update({
  id: '/news',
  path: '/news',
  getParentRoute: () => AppRoute,
} as any)
const AppContactRoute = AppContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => AppRoute,
} as any)
const AppAboutRoute = AppAboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => AppRoute,
} as any)
const AppUserRouteRoute = AppUserRouteRouteImport.update({
  id: '/user',
  path: '/user',
  getParentRoute: () => AppRoute,
} as any)
const AppLegalRouteRoute = AppLegalRouteRouteImport.update({
  id: '/legal',
  path: '/legal',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminRouteRoute = AppAdminRouteRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AppRoute,
} as any)
const AppUserIndexRoute = AppUserIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppUserRouteRoute,
} as any)
const AppDepartmentsIndexRoute = AppDepartmentsIndexRouteImport.update({
  id: '/departments/',
  path: '/departments/',
  getParentRoute: () => AppRoute,
} as any)
const AppBrowseIndexRoute = AppBrowseIndexRouteImport.update({
  id: '/browse/',
  path: '/browse/',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminIndexRoute = AppAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppAdminRouteRoute,
} as any)
const AppUserSettingsRoute = AppUserSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppUserRouteRoute,
} as any)
const AppUserProgressRoute = AppUserProgressRouteImport.update({
  id: '/progress',
  path: '/progress',
  getParentRoute: () => AppUserRouteRoute,
} as any)
const AppUserNotificationsRoute = AppUserNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => AppUserRouteRoute,
} as any)
const AppUserClassesRoute = AppUserClassesRouteImport.update({
  id: '/classes',
  path: '/classes',
  getParentRoute: () => AppUserRouteRoute,
} as any)
const AppUserBookmarksRoute = AppUserBookmarksRouteImport.update({
  id: '/bookmarks',
  path: '/bookmarks',
  getParentRoute: () => AppUserRouteRoute,
} as any)
const AppLegalTermsRoute = AppLegalTermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => AppLegalRouteRoute,
} as any)
const AppLegalPrivacyRoute = AppLegalPrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => AppLegalRouteRoute,
} as any)
const AppLegalDeclinedRoute = AppLegalDeclinedRouteImport.update({
  id: '/declined',
  path: '/declined',
  getParentRoute: () => AppLegalRouteRoute,
} as any)
const AppLegalCookiesRoute = AppLegalCookiesRouteImport.update({
  id: '/cookies',
  path: '/cookies',
  getParentRoute: () => AppLegalRouteRoute,
} as any)
const AppLegalAcceptRoute = AppLegalAcceptRouteImport.update({
  id: '/accept',
  path: '/accept',
  getParentRoute: () => AppLegalRouteRoute,
} as any)
const AppUserRequestsIndexRoute = AppUserRequestsIndexRouteImport.update({
  id: '/requests/',
  path: '/requests/',
  getParentRoute: () => AppUserRouteRoute,
} as any)
const AppSearchCoursesIndexRoute = AppSearchCoursesIndexRouteImport.update({
  id: '/search/courses/',
  path: '/search/courses/',
  getParentRoute: () => AppRoute,
} as any)
const AppSearchClassesIndexRoute = AppSearchClassesIndexRouteImport.update({
  id: '/search/classes/',
  path: '/search/classes/',
  getParentRoute: () => AppRoute,
} as any)
const AppDepartmentsDepartmentIndexRoute =
  AppDepartmentsDepartmentIndexRouteImport.update({
    id: '/departments/$department/',
    path: '/departments/$department/',
    getParentRoute: () => AppRoute,
  } as any)
const AppBrowseDepartmentIndexRoute =
  AppBrowseDepartmentIndexRouteImport.update({
    id: '/browse/$department/',
    path: '/browse/$department/',
    getParentRoute: () => AppRoute,
  } as any)
const AppAdminUsersIndexRoute = AppAdminUsersIndexRouteImport.update({
  id: '/users/',
  path: '/users/',
  getParentRoute: () => AppAdminRouteRoute,
} as any)
const AppAdminRequestsIndexRoute = AppAdminRequestsIndexRouteImport.update({
  id: '/requests/',
  path: '/requests/',
  getParentRoute: () => AppAdminRouteRoute,
} as any)
const AppAdminDepartmentsIndexRoute =
  AppAdminDepartmentsIndexRouteImport.update({
    id: '/departments/',
    path: '/departments/',
    getParentRoute: () => AppAdminRouteRoute,
  } as any)
const AppQuizResultsAttemptIdRoute = AppQuizResultsAttemptIdRouteImport.update({
  id: '/quiz/results/$attemptId',
  path: '/quiz/results/$attemptId',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminUsersUserIdRoute = AppAdminUsersUserIdRouteImport.update({
  id: '/users/$userId',
  path: '/users/$userId',
  getParentRoute: () => AppAdminRouteRoute,
} as any)
const AppAdminSectionsSectionIdRoute =
  AppAdminSectionsSectionIdRouteImport.update({
    id: '/sections/$sectionId',
    path: '/sections/$sectionId',
    getParentRoute: () => AppAdminRouteRoute,
  } as any)
const AppAdminRequestsRequestIdRoute =
  AppAdminRequestsRequestIdRouteImport.update({
    id: '/requests/$requestId',
    path: '/requests/$requestId',
    getParentRoute: () => AppAdminRouteRoute,
  } as any)
const AppAdminQuestionsQuestionIdRoute =
  AppAdminQuestionsQuestionIdRouteImport.update({
    id: '/questions/$questionId',
    path: '/questions/$questionId',
    getParentRoute: () => AppAdminRouteRoute,
  } as any)
const AppAdminDepartmentsDepartmentIdRoute =
  AppAdminDepartmentsDepartmentIdRouteImport.update({
    id: '/departments/$departmentId',
    path: '/departments/$departmentId',
    getParentRoute: () => AppAdminRouteRoute,
  } as any)
const AppAdminCoursesCourseIdRoute = AppAdminCoursesCourseIdRouteImport.update({
  id: '/courses/$courseId',
  path: '/courses/$courseId',
  getParentRoute: () => AppAdminRouteRoute,
} as any)
const AppAdminClassesClassIdRoute = AppAdminClassesClassIdRouteImport.update({
  id: '/classes/$classId',
  path: '/classes/$classId',
  getParentRoute: () => AppAdminRouteRoute,
} as any)
const AppDepartmentsDepartmentCourseIndexRoute =
  AppDepartmentsDepartmentCourseIndexRouteImport.update({
    id: '/departments/$department/$course/',
    path: '/departments/$department/$course/',
    getParentRoute: () => AppRoute,
  } as any)
const AppBrowseDepartmentCourseIndexRoute =
  AppBrowseDepartmentCourseIndexRouteImport.update({
    id: '/browse/$department/$course/',
    path: '/browse/$department/$course/',
    getParentRoute: () => AppRoute,
  } as any)
const AppDepartmentsDepartmentCourseClassIndexRoute =
  AppDepartmentsDepartmentCourseClassIndexRouteImport.update({
    id: '/departments/$department/$course/$class/',
    path: '/departments/$department/$course/$class/',
    getParentRoute: () => AppRoute,
  } as any)
const AppBrowseDepartmentCourseClassIndexRoute =
  AppBrowseDepartmentCourseClassIndexRouteImport.update({
    id: '/browse/$department/$course/$class/',
    path: '/browse/$department/$course/$class/',
    getParentRoute: () => AppRoute,
  } as any)
const AppDepartmentsDepartmentCourseClassSectionIndexRoute =
  AppDepartmentsDepartmentCourseClassSectionIndexRouteImport.update({
    id: '/departments/$department/$course/$class/$section/',
    path: '/departments/$department/$course/$class/$section/',
    getParentRoute: () => AppRoute,
  } as any)
const AppBrowseDepartmentCourseClassSectionIndexRoute =
  AppBrowseDepartmentCourseClassSectionIndexRouteImport.update({
    id: '/browse/$department/$course/$class/$section/',
    path: '/browse/$department/$course/$class/$section/',
    getParentRoute: () => AppRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/maintenance': typeof MaintenanceRoute
  '/admin': typeof AppAdminRouteRouteWithChildren
  '/legal': typeof AppLegalRouteRouteWithChildren
  '/user': typeof AppUserRouteRouteWithChildren
  '/about': typeof AppAboutRoute
  '/contact': typeof AppContactRoute
  '/news': typeof AppNewsRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/register': typeof AuthRegisterRoute
  '/flashcard/$sessionId': typeof FlashcardSessionIdRoute
  '/quiz/$quizId': typeof QuizQuizIdRoute
  '/legal/accept': typeof AppLegalAcceptRoute
  '/legal/cookies': typeof AppLegalCookiesRoute
  '/legal/declined': typeof AppLegalDeclinedRoute
  '/legal/privacy': typeof AppLegalPrivacyRoute
  '/legal/terms': typeof AppLegalTermsRoute
  '/user/bookmarks': typeof AppUserBookmarksRoute
  '/user/classes': typeof AppUserClassesRoute
  '/user/notifications': typeof AppUserNotificationsRoute
  '/user/progress': typeof AppUserProgressRoute
  '/user/settings': typeof AppUserSettingsRoute
  '/admin/': typeof AppAdminIndexRoute
  '/browse/': typeof AppBrowseIndexRoute
  '/departments/': typeof AppDepartmentsIndexRoute
  '/user/': typeof AppUserIndexRoute
  '/admin/classes/$classId': typeof AppAdminClassesClassIdRoute
  '/admin/courses/$courseId': typeof AppAdminCoursesCourseIdRoute
  '/admin/departments/$departmentId': typeof AppAdminDepartmentsDepartmentIdRoute
  '/admin/questions/$questionId': typeof AppAdminQuestionsQuestionIdRoute
  '/admin/requests/$requestId': typeof AppAdminRequestsRequestIdRoute
  '/admin/sections/$sectionId': typeof AppAdminSectionsSectionIdRoute
  '/admin/users/$userId': typeof AppAdminUsersUserIdRoute
  '/quiz/results/$attemptId': typeof AppQuizResultsAttemptIdRoute
  '/admin/departments/': typeof AppAdminDepartmentsIndexRoute
  '/admin/requests/': typeof AppAdminRequestsIndexRoute
  '/admin/users/': typeof AppAdminUsersIndexRoute
  '/browse/$department/': typeof AppBrowseDepartmentIndexRoute
  '/departments/$department/': typeof AppDepartmentsDepartmentIndexRoute
  '/search/classes/': typeof AppSearchClassesIndexRoute
  '/search/courses/': typeof AppSearchCoursesIndexRoute
  '/user/requests/': typeof AppUserRequestsIndexRoute
  '/browse/$department/$course/': typeof AppBrowseDepartmentCourseIndexRoute
  '/departments/$department/$course/': typeof AppDepartmentsDepartmentCourseIndexRoute
  '/browse/$department/$course/$class/': typeof AppBrowseDepartmentCourseClassIndexRoute
  '/departments/$department/$course/$class/': typeof AppDepartmentsDepartmentCourseClassIndexRoute
  '/browse/$department/$course/$class/$section/': typeof AppBrowseDepartmentCourseClassSectionIndexRoute
  '/departments/$department/$course/$class/$section/': typeof AppDepartmentsDepartmentCourseClassSectionIndexRoute
}
export interface FileRoutesByTo {
  '/maintenance': typeof MaintenanceRoute
  '/legal': typeof AppLegalRouteRouteWithChildren
  '/about': typeof AppAboutRoute
  '/contact': typeof AppContactRoute
  '/news': typeof AppNewsRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/register': typeof AuthRegisterRoute
  '/flashcard/$sessionId': typeof FlashcardSessionIdRoute
  '/quiz/$quizId': typeof QuizQuizIdRoute
  '/': typeof AppIndexRoute
  '/legal/accept': typeof AppLegalAcceptRoute
  '/legal/cookies': typeof AppLegalCookiesRoute
  '/legal/declined': typeof AppLegalDeclinedRoute
  '/legal/privacy': typeof AppLegalPrivacyRoute
  '/legal/terms': typeof AppLegalTermsRoute
  '/user/bookmarks': typeof AppUserBookmarksRoute
  '/user/classes': typeof AppUserClassesRoute
  '/user/notifications': typeof AppUserNotificationsRoute
  '/user/progress': typeof AppUserProgressRoute
  '/user/settings': typeof AppUserSettingsRoute
  '/admin': typeof AppAdminIndexRoute
  '/browse': typeof AppBrowseIndexRoute
  '/departments': typeof AppDepartmentsIndexRoute
  '/user': typeof AppUserIndexRoute
  '/admin/classes/$classId': typeof AppAdminClassesClassIdRoute
  '/admin/courses/$courseId': typeof AppAdminCoursesCourseIdRoute
  '/admin/departments/$departmentId': typeof AppAdminDepartmentsDepartmentIdRoute
  '/admin/questions/$questionId': typeof AppAdminQuestionsQuestionIdRoute
  '/admin/requests/$requestId': typeof AppAdminRequestsRequestIdRoute
  '/admin/sections/$sectionId': typeof AppAdminSectionsSectionIdRoute
  '/admin/users/$userId': typeof AppAdminUsersUserIdRoute
  '/quiz/results/$attemptId': typeof AppQuizResultsAttemptIdRoute
  '/admin/departments': typeof AppAdminDepartmentsIndexRoute
  '/admin/requests': typeof AppAdminRequestsIndexRoute
  '/admin/users': typeof AppAdminUsersIndexRoute
  '/browse/$department': typeof AppBrowseDepartmentIndexRoute
  '/departments/$department': typeof AppDepartmentsDepartmentIndexRoute
  '/search/classes': typeof AppSearchClassesIndexRoute
  '/search/courses': typeof AppSearchCoursesIndexRoute
  '/user/requests': typeof AppUserRequestsIndexRoute
  '/browse/$department/$course': typeof AppBrowseDepartmentCourseIndexRoute
  '/departments/$department/$course': typeof AppDepartmentsDepartmentCourseIndexRoute
  '/browse/$department/$course/$class': typeof AppBrowseDepartmentCourseClassIndexRoute
  '/departments/$department/$course/$class': typeof AppDepartmentsDepartmentCourseClassIndexRoute
  '/browse/$department/$course/$class/$section': typeof AppBrowseDepartmentCourseClassSectionIndexRoute
  '/departments/$department/$course/$class/$section': typeof AppDepartmentsDepartmentCourseClassSectionIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/maintenance': typeof MaintenanceRoute
  '/_app/admin': typeof AppAdminRouteRouteWithChildren
  '/_app/legal': typeof AppLegalRouteRouteWithChildren
  '/_app/user': typeof AppUserRouteRouteWithChildren
  '/_app/about': typeof AppAboutRoute
  '/_app/contact': typeof AppContactRoute
  '/_app/news': typeof AppNewsRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/register': typeof AuthRegisterRoute
  '/flashcard/$sessionId': typeof FlashcardSessionIdRoute
  '/quiz/$quizId': typeof QuizQuizIdRoute
  '/_app/': typeof AppIndexRoute
  '/_app/legal/accept': typeof AppLegalAcceptRoute
  '/_app/legal/cookies': typeof AppLegalCookiesRoute
  '/_app/legal/declined': typeof AppLegalDeclinedRoute
  '/_app/legal/privacy': typeof AppLegalPrivacyRoute
  '/_app/legal/terms': typeof AppLegalTermsRoute
  '/_app/user/bookmarks': typeof AppUserBookmarksRoute
  '/_app/user/classes': typeof AppUserClassesRoute
  '/_app/user/notifications': typeof AppUserNotificationsRoute
  '/_app/user/progress': typeof AppUserProgressRoute
  '/_app/user/settings': typeof AppUserSettingsRoute
  '/_app/admin/': typeof AppAdminIndexRoute
  '/_app/browse/': typeof AppBrowseIndexRoute
  '/_app/departments/': typeof AppDepartmentsIndexRoute
  '/_app/user/': typeof AppUserIndexRoute
  '/_app/admin/classes/$classId': typeof AppAdminClassesClassIdRoute
  '/_app/admin/courses/$courseId': typeof AppAdminCoursesCourseIdRoute
  '/_app/admin/departments/$departmentId': typeof AppAdminDepartmentsDepartmentIdRoute
  '/_app/admin/questions/$questionId': typeof AppAdminQuestionsQuestionIdRoute
  '/_app/admin/requests/$requestId': typeof AppAdminRequestsRequestIdRoute
  '/_app/admin/sections/$sectionId': typeof AppAdminSectionsSectionIdRoute
  '/_app/admin/users/$userId': typeof AppAdminUsersUserIdRoute
  '/_app/quiz/results/$attemptId': typeof AppQuizResultsAttemptIdRoute
  '/_app/admin/departments/': typeof AppAdminDepartmentsIndexRoute
  '/_app/admin/requests/': typeof AppAdminRequestsIndexRoute
  '/_app/admin/users/': typeof AppAdminUsersIndexRoute
  '/_app/browse/$department/': typeof AppBrowseDepartmentIndexRoute
  '/_app/departments/$department/': typeof AppDepartmentsDepartmentIndexRoute
  '/_app/search/classes/': typeof AppSearchClassesIndexRoute
  '/_app/search/courses/': typeof AppSearchCoursesIndexRoute
  '/_app/user/requests/': typeof AppUserRequestsIndexRoute
  '/_app/browse/$department/$course/': typeof AppBrowseDepartmentCourseIndexRoute
  '/_app/departments/$department/$course/': typeof AppDepartmentsDepartmentCourseIndexRoute
  '/_app/browse/$department/$course/$class/': typeof AppBrowseDepartmentCourseClassIndexRoute
  '/_app/departments/$department/$course/$class/': typeof AppDepartmentsDepartmentCourseClassIndexRoute
  '/_app/browse/$department/$course/$class/$section/': typeof AppBrowseDepartmentCourseClassSectionIndexRoute
  '/_app/departments/$department/$course/$class/$section/': typeof AppDepartmentsDepartmentCourseClassSectionIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/maintenance'
    | '/admin'
    | '/legal'
    | '/user'
    | '/about'
    | '/contact'
    | '/news'
    | '/auth/callback'
    | '/auth/login'
    | '/auth/register'
    | '/flashcard/$sessionId'
    | '/quiz/$quizId'
    | '/legal/accept'
    | '/legal/cookies'
    | '/legal/declined'
    | '/legal/privacy'
    | '/legal/terms'
    | '/user/bookmarks'
    | '/user/classes'
    | '/user/notifications'
    | '/user/progress'
    | '/user/settings'
    | '/admin/'
    | '/browse/'
    | '/departments/'
    | '/user/'
    | '/admin/classes/$classId'
    | '/admin/courses/$courseId'
    | '/admin/departments/$departmentId'
    | '/admin/questions/$questionId'
    | '/admin/requests/$requestId'
    | '/admin/sections/$sectionId'
    | '/admin/users/$userId'
    | '/quiz/results/$attemptId'
    | '/admin/departments/'
    | '/admin/requests/'
    | '/admin/users/'
    | '/browse/$department/'
    | '/departments/$department/'
    | '/search/classes/'
    | '/search/courses/'
    | '/user/requests/'
    | '/browse/$department/$course/'
    | '/departments/$department/$course/'
    | '/browse/$department/$course/$class/'
    | '/departments/$department/$course/$class/'
    | '/browse/$department/$course/$class/$section/'
    | '/departments/$department/$course/$class/$section/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/maintenance'
    | '/legal'
    | '/about'
    | '/contact'
    | '/news'
    | '/auth/callback'
    | '/auth/login'
    | '/auth/register'
    | '/flashcard/$sessionId'
    | '/quiz/$quizId'
    | '/'
    | '/legal/accept'
    | '/legal/cookies'
    | '/legal/declined'
    | '/legal/privacy'
    | '/legal/terms'
    | '/user/bookmarks'
    | '/user/classes'
    | '/user/notifications'
    | '/user/progress'
    | '/user/settings'
    | '/admin'
    | '/browse'
    | '/departments'
    | '/user'
    | '/admin/classes/$classId'
    | '/admin/courses/$courseId'
    | '/admin/departments/$departmentId'
    | '/admin/questions/$questionId'
    | '/admin/requests/$requestId'
    | '/admin/sections/$sectionId'
    | '/admin/users/$userId'
    | '/quiz/results/$attemptId'
    | '/admin/departments'
    | '/admin/requests'
    | '/admin/users'
    | '/browse/$department'
    | '/departments/$department'
    | '/search/classes'
    | '/search/courses'
    | '/user/requests'
    | '/browse/$department/$course'
    | '/departments/$department/$course'
    | '/browse/$department/$course/$class'
    | '/departments/$department/$course/$class'
    | '/browse/$department/$course/$class/$section'
    | '/departments/$department/$course/$class/$section'
  id:
    | '__root__'
    | '/_app'
    | '/maintenance'
    | '/_app/admin'
    | '/_app/legal'
    | '/_app/user'
    | '/_app/about'
    | '/_app/contact'
    | '/_app/news'
    | '/auth/callback'
    | '/auth/login'
    | '/auth/register'
    | '/flashcard/$sessionId'
    | '/quiz/$quizId'
    | '/_app/'
    | '/_app/legal/accept'
    | '/_app/legal/cookies'
    | '/_app/legal/declined'
    | '/_app/legal/privacy'
    | '/_app/legal/terms'
    | '/_app/user/bookmarks'
    | '/_app/user/classes'
    | '/_app/user/notifications'
    | '/_app/user/progress'
    | '/_app/user/settings'
    | '/_app/admin/'
    | '/_app/browse/'
    | '/_app/departments/'
    | '/_app/user/'
    | '/_app/admin/classes/$classId'
    | '/_app/admin/courses/$courseId'
    | '/_app/admin/departments/$departmentId'
    | '/_app/admin/questions/$questionId'
    | '/_app/admin/requests/$requestId'
    | '/_app/admin/sections/$sectionId'
    | '/_app/admin/users/$userId'
    | '/_app/quiz/results/$attemptId'
    | '/_app/admin/departments/'
    | '/_app/admin/requests/'
    | '/_app/admin/users/'
    | '/_app/browse/$department/'
    | '/_app/departments/$department/'
    | '/_app/search/classes/'
    | '/_app/search/courses/'
    | '/_app/user/requests/'
    | '/_app/browse/$department/$course/'
    | '/_app/departments/$department/$course/'
    | '/_app/browse/$department/$course/$class/'
    | '/_app/departments/$department/$course/$class/'
    | '/_app/browse/$department/$course/$class/$section/'
    | '/_app/departments/$department/$course/$class/$section/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
  MaintenanceRoute: typeof MaintenanceRoute
  AuthCallbackRoute: typeof AuthCallbackRoute
  AuthLoginRoute: typeof AuthLoginRoute
  AuthRegisterRoute: typeof AuthRegisterRoute
  FlashcardSessionIdRoute: typeof FlashcardSessionIdRoute
  QuizQuizIdRoute: typeof QuizQuizIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/maintenance': {
      id: '/maintenance'
      path: '/maintenance'
      fullPath: '/maintenance'
      preLoaderRoute: typeof MaintenanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/quiz/$quizId': {
      id: '/quiz/$quizId'
      path: '/quiz/$quizId'
      fullPath: '/quiz/$quizId'
      preLoaderRoute: typeof QuizQuizIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/flashcard/$sessionId': {
      id: '/flashcard/$sessionId'
      path: '/flashcard/$sessionId'
      fullPath: '/flashcard/$sessionId'
      preLoaderRoute: typeof FlashcardSessionIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/register': {
      id: '/auth/register'
      path: '/auth/register'
      fullPath: '/auth/register'
      preLoaderRoute: typeof AuthRegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/login': {
      id: '/auth/login'
      path: '/auth/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/callback': {
      id: '/auth/callback'
      path: '/auth/callback'
      fullPath: '/auth/callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/news': {
      id: '/_app/news'
      path: '/news'
      fullPath: '/news'
      preLoaderRoute: typeof AppNewsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/contact': {
      id: '/_app/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof AppContactRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/about': {
      id: '/_app/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AppAboutRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/user': {
      id: '/_app/user'
      path: '/user'
      fullPath: '/user'
      preLoaderRoute: typeof AppUserRouteRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/legal': {
      id: '/_app/legal'
      path: '/legal'
      fullPath: '/legal'
      preLoaderRoute: typeof AppLegalRouteRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/admin': {
      id: '/_app/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AppAdminRouteRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/user/': {
      id: '/_app/user/'
      path: '/'
      fullPath: '/user/'
      preLoaderRoute: typeof AppUserIndexRouteImport
      parentRoute: typeof AppUserRouteRoute
    }
    '/_app/departments/': {
      id: '/_app/departments/'
      path: '/departments'
      fullPath: '/departments/'
      preLoaderRoute: typeof AppDepartmentsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/browse/': {
      id: '/_app/browse/'
      path: '/browse'
      fullPath: '/browse/'
      preLoaderRoute: typeof AppBrowseIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/admin/': {
      id: '/_app/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AppAdminIndexRouteImport
      parentRoute: typeof AppAdminRouteRoute
    }
    '/_app/user/settings': {
      id: '/_app/user/settings'
      path: '/settings'
      fullPath: '/user/settings'
      preLoaderRoute: typeof AppUserSettingsRouteImport
      parentRoute: typeof AppUserRouteRoute
    }
    '/_app/user/progress': {
      id: '/_app/user/progress'
      path: '/progress'
      fullPath: '/user/progress'
      preLoaderRoute: typeof AppUserProgressRouteImport
      parentRoute: typeof AppUserRouteRoute
    }
    '/_app/user/notifications': {
      id: '/_app/user/notifications'
      path: '/notifications'
      fullPath: '/user/notifications'
      preLoaderRoute: typeof AppUserNotificationsRouteImport
      parentRoute: typeof AppUserRouteRoute
    }
    '/_app/user/classes': {
      id: '/_app/user/classes'
      path: '/classes'
      fullPath: '/user/classes'
      preLoaderRoute: typeof AppUserClassesRouteImport
      parentRoute: typeof AppUserRouteRoute
    }
    '/_app/user/bookmarks': {
      id: '/_app/user/bookmarks'
      path: '/bookmarks'
      fullPath: '/user/bookmarks'
      preLoaderRoute: typeof AppUserBookmarksRouteImport
      parentRoute: typeof AppUserRouteRoute
    }
    '/_app/legal/terms': {
      id: '/_app/legal/terms'
      path: '/terms'
      fullPath: '/legal/terms'
      preLoaderRoute: typeof AppLegalTermsRouteImport
      parentRoute: typeof AppLegalRouteRoute
    }
    '/_app/legal/privacy': {
      id: '/_app/legal/privacy'
      path: '/privacy'
      fullPath: '/legal/privacy'
      preLoaderRoute: typeof AppLegalPrivacyRouteImport
      parentRoute: typeof AppLegalRouteRoute
    }
    '/_app/legal/declined': {
      id: '/_app/legal/declined'
      path: '/declined'
      fullPath: '/legal/declined'
      preLoaderRoute: typeof AppLegalDeclinedRouteImport
      parentRoute: typeof AppLegalRouteRoute
    }
    '/_app/legal/cookies': {
      id: '/_app/legal/cookies'
      path: '/cookies'
      fullPath: '/legal/cookies'
      preLoaderRoute: typeof AppLegalCookiesRouteImport
      parentRoute: typeof AppLegalRouteRoute
    }
    '/_app/legal/accept': {
      id: '/_app/legal/accept'
      path: '/accept'
      fullPath: '/legal/accept'
      preLoaderRoute: typeof AppLegalAcceptRouteImport
      parentRoute: typeof AppLegalRouteRoute
    }
    '/_app/user/requests/': {
      id: '/_app/user/requests/'
      path: '/requests'
      fullPath: '/user/requests/'
      preLoaderRoute: typeof AppUserRequestsIndexRouteImport
      parentRoute: typeof AppUserRouteRoute
    }
    '/_app/search/courses/': {
      id: '/_app/search/courses/'
      path: '/search/courses'
      fullPath: '/search/courses/'
      preLoaderRoute: typeof AppSearchCoursesIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/search/classes/': {
      id: '/_app/search/classes/'
      path: '/search/classes'
      fullPath: '/search/classes/'
      preLoaderRoute: typeof AppSearchClassesIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/departments/$department/': {
      id: '/_app/departments/$department/'
      path: '/departments/$department'
      fullPath: '/departments/$department/'
      preLoaderRoute: typeof AppDepartmentsDepartmentIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/browse/$department/': {
      id: '/_app/browse/$department/'
      path: '/browse/$department'
      fullPath: '/browse/$department/'
      preLoaderRoute: typeof AppBrowseDepartmentIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/admin/users/': {
      id: '/_app/admin/users/'
      path: '/users'
      fullPath: '/admin/users/'
      preLoaderRoute: typeof AppAdminUsersIndexRouteImport
      parentRoute: typeof AppAdminRouteRoute
    }
    '/_app/admin/requests/': {
      id: '/_app/admin/requests/'
      path: '/requests'
      fullPath: '/admin/requests/'
      preLoaderRoute: typeof AppAdminRequestsIndexRouteImport
      parentRoute: typeof AppAdminRouteRoute
    }
    '/_app/admin/departments/': {
      id: '/_app/admin/departments/'
      path: '/departments'
      fullPath: '/admin/departments/'
      preLoaderRoute: typeof AppAdminDepartmentsIndexRouteImport
      parentRoute: typeof AppAdminRouteRoute
    }
    '/_app/quiz/results/$attemptId': {
      id: '/_app/quiz/results/$attemptId'
      path: '/quiz/results/$attemptId'
      fullPath: '/quiz/results/$attemptId'
      preLoaderRoute: typeof AppQuizResultsAttemptIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/admin/users/$userId': {
      id: '/_app/admin/users/$userId'
      path: '/users/$userId'
      fullPath: '/admin/users/$userId'
      preLoaderRoute: typeof AppAdminUsersUserIdRouteImport
      parentRoute: typeof AppAdminRouteRoute
    }
    '/_app/admin/sections/$sectionId': {
      id: '/_app/admin/sections/$sectionId'
      path: '/sections/$sectionId'
      fullPath: '/admin/sections/$sectionId'
      preLoaderRoute: typeof AppAdminSectionsSectionIdRouteImport
      parentRoute: typeof AppAdminRouteRoute
    }
    '/_app/admin/requests/$requestId': {
      id: '/_app/admin/requests/$requestId'
      path: '/requests/$requestId'
      fullPath: '/admin/requests/$requestId'
      preLoaderRoute: typeof AppAdminRequestsRequestIdRouteImport
      parentRoute: typeof AppAdminRouteRoute
    }
    '/_app/admin/questions/$questionId': {
      id: '/_app/admin/questions/$questionId'
      path: '/questions/$questionId'
      fullPath: '/admin/questions/$questionId'
      preLoaderRoute: typeof AppAdminQuestionsQuestionIdRouteImport
      parentRoute: typeof AppAdminRouteRoute
    }
    '/_app/admin/departments/$departmentId': {
      id: '/_app/admin/departments/$departmentId'
      path: '/departments/$departmentId'
      fullPath: '/admin/departments/$departmentId'
      preLoaderRoute: typeof AppAdminDepartmentsDepartmentIdRouteImport
      parentRoute: typeof AppAdminRouteRoute
    }
    '/_app/admin/courses/$courseId': {
      id: '/_app/admin/courses/$courseId'
      path: '/courses/$courseId'
      fullPath: '/admin/courses/$courseId'
      preLoaderRoute: typeof AppAdminCoursesCourseIdRouteImport
      parentRoute: typeof AppAdminRouteRoute
    }
    '/_app/admin/classes/$classId': {
      id: '/_app/admin/classes/$classId'
      path: '/classes/$classId'
      fullPath: '/admin/classes/$classId'
      preLoaderRoute: typeof AppAdminClassesClassIdRouteImport
      parentRoute: typeof AppAdminRouteRoute
    }
    '/_app/departments/$department/$course/': {
      id: '/_app/departments/$department/$course/'
      path: '/departments/$department/$course'
      fullPath: '/departments/$department/$course/'
      preLoaderRoute: typeof AppDepartmentsDepartmentCourseIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/browse/$department/$course/': {
      id: '/_app/browse/$department/$course/'
      path: '/browse/$department/$course'
      fullPath: '/browse/$department/$course/'
      preLoaderRoute: typeof AppBrowseDepartmentCourseIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/departments/$department/$course/$class/': {
      id: '/_app/departments/$department/$course/$class/'
      path: '/departments/$department/$course/$class'
      fullPath: '/departments/$department/$course/$class/'
      preLoaderRoute: typeof AppDepartmentsDepartmentCourseClassIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/browse/$department/$course/$class/': {
      id: '/_app/browse/$department/$course/$class/'
      path: '/browse/$department/$course/$class'
      fullPath: '/browse/$department/$course/$class/'
      preLoaderRoute: typeof AppBrowseDepartmentCourseClassIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/departments/$department/$course/$class/$section/': {
      id: '/_app/departments/$department/$course/$class/$section/'
      path: '/departments/$department/$course/$class/$section'
      fullPath: '/departments/$department/$course/$class/$section/'
      preLoaderRoute: typeof AppDepartmentsDepartmentCourseClassSectionIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/browse/$department/$course/$class/$section/': {
      id: '/_app/browse/$department/$course/$class/$section/'
      path: '/browse/$department/$course/$class/$section'
      fullPath: '/browse/$department/$course/$class/$section/'
      preLoaderRoute: typeof AppBrowseDepartmentCourseClassSectionIndexRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppAdminRouteRouteChildren {
  AppAdminIndexRoute: typeof AppAdminIndexRoute
  AppAdminClassesClassIdRoute: typeof AppAdminClassesClassIdRoute
  AppAdminCoursesCourseIdRoute: typeof AppAdminCoursesCourseIdRoute
  AppAdminDepartmentsDepartmentIdRoute: typeof AppAdminDepartmentsDepartmentIdRoute
  AppAdminQuestionsQuestionIdRoute: typeof AppAdminQuestionsQuestionIdRoute
  AppAdminRequestsRequestIdRoute: typeof AppAdminRequestsRequestIdRoute
  AppAdminSectionsSectionIdRoute: typeof AppAdminSectionsSectionIdRoute
  AppAdminUsersUserIdRoute: typeof AppAdminUsersUserIdRoute
  AppAdminDepartmentsIndexRoute: typeof AppAdminDepartmentsIndexRoute
  AppAdminRequestsIndexRoute: typeof AppAdminRequestsIndexRoute
  AppAdminUsersIndexRoute: typeof AppAdminUsersIndexRoute
}

const AppAdminRouteRouteChildren: AppAdminRouteRouteChildren = {
  AppAdminIndexRoute: AppAdminIndexRoute,
  AppAdminClassesClassIdRoute: AppAdminClassesClassIdRoute,
  AppAdminCoursesCourseIdRoute: AppAdminCoursesCourseIdRoute,
  AppAdminDepartmentsDepartmentIdRoute: AppAdminDepartmentsDepartmentIdRoute,
  AppAdminQuestionsQuestionIdRoute: AppAdminQuestionsQuestionIdRoute,
  AppAdminRequestsRequestIdRoute: AppAdminRequestsRequestIdRoute,
  AppAdminSectionsSectionIdRoute: AppAdminSectionsSectionIdRoute,
  AppAdminUsersUserIdRoute: AppAdminUsersUserIdRoute,
  AppAdminDepartmentsIndexRoute: AppAdminDepartmentsIndexRoute,
  AppAdminRequestsIndexRoute: AppAdminRequestsIndexRoute,
  AppAdminUsersIndexRoute: AppAdminUsersIndexRoute,
}

const AppAdminRouteRouteWithChildren = AppAdminRouteRoute._addFileChildren(
  AppAdminRouteRouteChildren,
)

interface AppLegalRouteRouteChildren {
  AppLegalAcceptRoute: typeof AppLegalAcceptRoute
  AppLegalCookiesRoute: typeof AppLegalCookiesRoute
  AppLegalDeclinedRoute: typeof AppLegalDeclinedRoute
  AppLegalPrivacyRoute: typeof AppLegalPrivacyRoute
  AppLegalTermsRoute: typeof AppLegalTermsRoute
}

const AppLegalRouteRouteChildren: AppLegalRouteRouteChildren = {
  AppLegalAcceptRoute: AppLegalAcceptRoute,
  AppLegalCookiesRoute: AppLegalCookiesRoute,
  AppLegalDeclinedRoute: AppLegalDeclinedRoute,
  AppLegalPrivacyRoute: AppLegalPrivacyRoute,
  AppLegalTermsRoute: AppLegalTermsRoute,
}

const AppLegalRouteRouteWithChildren = AppLegalRouteRoute._addFileChildren(
  AppLegalRouteRouteChildren,
)

interface AppUserRouteRouteChildren {
  AppUserBookmarksRoute: typeof AppUserBookmarksRoute
  AppUserClassesRoute: typeof AppUserClassesRoute
  AppUserNotificationsRoute: typeof AppUserNotificationsRoute
  AppUserProgressRoute: typeof AppUserProgressRoute
  AppUserSettingsRoute: typeof AppUserSettingsRoute
  AppUserIndexRoute: typeof AppUserIndexRoute
  AppUserRequestsIndexRoute: typeof AppUserRequestsIndexRoute
}

const AppUserRouteRouteChildren: AppUserRouteRouteChildren = {
  AppUserBookmarksRoute: AppUserBookmarksRoute,
  AppUserClassesRoute: AppUserClassesRoute,
  AppUserNotificationsRoute: AppUserNotificationsRoute,
  AppUserProgressRoute: AppUserProgressRoute,
  AppUserSettingsRoute: AppUserSettingsRoute,
  AppUserIndexRoute: AppUserIndexRoute,
  AppUserRequestsIndexRoute: AppUserRequestsIndexRoute,
}

const AppUserRouteRouteWithChildren = AppUserRouteRoute._addFileChildren(
  AppUserRouteRouteChildren,
)

interface AppRouteChildren {
  AppAdminRouteRoute: typeof AppAdminRouteRouteWithChildren
  AppLegalRouteRoute: typeof AppLegalRouteRouteWithChildren
  AppUserRouteRoute: typeof AppUserRouteRouteWithChildren
  AppAboutRoute: typeof AppAboutRoute
  AppContactRoute: typeof AppContactRoute
  AppNewsRoute: typeof AppNewsRoute
  AppIndexRoute: typeof AppIndexRoute
  AppBrowseIndexRoute: typeof AppBrowseIndexRoute
  AppDepartmentsIndexRoute: typeof AppDepartmentsIndexRoute
  AppQuizResultsAttemptIdRoute: typeof AppQuizResultsAttemptIdRoute
  AppBrowseDepartmentIndexRoute: typeof AppBrowseDepartmentIndexRoute
  AppDepartmentsDepartmentIndexRoute: typeof AppDepartmentsDepartmentIndexRoute
  AppSearchClassesIndexRoute: typeof AppSearchClassesIndexRoute
  AppSearchCoursesIndexRoute: typeof AppSearchCoursesIndexRoute
  AppBrowseDepartmentCourseIndexRoute: typeof AppBrowseDepartmentCourseIndexRoute
  AppDepartmentsDepartmentCourseIndexRoute: typeof AppDepartmentsDepartmentCourseIndexRoute
  AppBrowseDepartmentCourseClassIndexRoute: typeof AppBrowseDepartmentCourseClassIndexRoute
  AppDepartmentsDepartmentCourseClassIndexRoute: typeof AppDepartmentsDepartmentCourseClassIndexRoute
  AppBrowseDepartmentCourseClassSectionIndexRoute: typeof AppBrowseDepartmentCourseClassSectionIndexRoute
  AppDepartmentsDepartmentCourseClassSectionIndexRoute: typeof AppDepartmentsDepartmentCourseClassSectionIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAdminRouteRoute: AppAdminRouteRouteWithChildren,
  AppLegalRouteRoute: AppLegalRouteRouteWithChildren,
  AppUserRouteRoute: AppUserRouteRouteWithChildren,
  AppAboutRoute: AppAboutRoute,
  AppContactRoute: AppContactRoute,
  AppNewsRoute: AppNewsRoute,
  AppIndexRoute: AppIndexRoute,
  AppBrowseIndexRoute: AppBrowseIndexRoute,
  AppDepartmentsIndexRoute: AppDepartmentsIndexRoute,
  AppQuizResultsAttemptIdRoute: AppQuizResultsAttemptIdRoute,
  AppBrowseDepartmentIndexRoute: AppBrowseDepartmentIndexRoute,
  AppDepartmentsDepartmentIndexRoute: AppDepartmentsDepartmentIndexRoute,
  AppSearchClassesIndexRoute: AppSearchClassesIndexRoute,
  AppSearchCoursesIndexRoute: AppSearchCoursesIndexRoute,
  AppBrowseDepartmentCourseIndexRoute: AppBrowseDepartmentCourseIndexRoute,
  AppDepartmentsDepartmentCourseIndexRoute:
    AppDepartmentsDepartmentCourseIndexRoute,
  AppBrowseDepartmentCourseClassIndexRoute:
    AppBrowseDepartmentCourseClassIndexRoute,
  AppDepartmentsDepartmentCourseClassIndexRoute:
    AppDepartmentsDepartmentCourseClassIndexRoute,
  AppBrowseDepartmentCourseClassSectionIndexRoute:
    AppBrowseDepartmentCourseClassSectionIndexRoute,
  AppDepartmentsDepartmentCourseClassSectionIndexRoute:
    AppDepartmentsDepartmentCourseClassSectionIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
  MaintenanceRoute: MaintenanceRoute,
  AuthCallbackRoute: AuthCallbackRoute,
  AuthLoginRoute: AuthLoginRoute,
  AuthRegisterRoute: AuthRegisterRoute,
  FlashcardSessionIdRoute: FlashcardSessionIdRoute,
  QuizQuizIdRoute: QuizQuizIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
